### ISSUE TITLE
Infinite Redirect on login, PHP ERROR Call to a member function is_temptable() on null 

### ISSUE THREAD

**Issue by pkeogan** [catalyst/moodle-auth_saml2#280]
I have moodle setup as a SP and a Laravel server setup as an IDP.

Sending the AuthnRequest works fine. It is responding with the following XML SAML Response. 

```
<?xml version="1.0" encoding="UTF-8"?>
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="_21cd45e73cd81a9e222c639f8d2be62664d5576d8c" Version="2.0" IssueInstant="2018-09-04T20:18:07Z" Destination="https://moodle.somewebsite.org/auth/saml2/sp/saml2-acs.php/moodle.somewebsite.org">
   <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://somewebsite.org</saml:Issuer>
   <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo>
         <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
         <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
         <ds:Reference URI="#_21cd45e73cd81a9e222c639f8d2be62664d5576d8c">
            <ds:Transforms>
               <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
               <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            </ds:Transforms>
            <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
            <ds:DigestValue>kT/5pTT33AIRwos+b+GfjHKqmoC6Y5pvdqPrHmacbGo=</ds:DigestValue>
         </ds:Reference>
      </ds:SignedInfo>
      <ds:SignatureValue>2DbbF.....</ds:SignatureValue>
      <ds:KeyInfo>
         <ds:X509Data>
            <ds:X509Certificate>MIID6zCC....</ds:X509Certificate>
         </ds:X509Data>
      </ds:KeyInfo>
   </ds:Signature>
   <samlp:Status>
      <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
   </samlp:Status>
   <Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="_446be83a66fe4a9b41bd024263aa1e734ff0121063" Version="2.0" IssueInstant="2018-09-04T20:18:07Z">
      <Issuer>https://somewebsite.org</Issuer>
      <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
         <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
            <ds:Reference URI="#_446be83a66fe4a9b41bd024263aa1e734ff0121063">
               <ds:Transforms>
                  <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                  <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
               </ds:Transforms>
               <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
               <ds:DigestValue>9Im4x6A3qjAw0ItSNzxPsFqb5ECrE8oeGvEYBRIy4Nk=</ds:DigestValue>
            </ds:Reference>
         </ds:SignedInfo>
         <ds:SignatureValue>mN6wt+rh+CZ....</ds:SignatureValue>
         <ds:KeyInfo>
            <ds:X509Data>
               <ds:X509Certificate>MIID6z...</ds:X509Certificate>
            </ds:X509Data>
         </ds:KeyInfo>
      </ds:Signature>
      <Subject>
         <NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">user@somewebsite.org</NameID>
         <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
            <SubjectConfirmationData InResponseTo="_b0a18a3f3a69f3c663607a1e3bc953b4d5a713801d" NotOnOrAfter="2018-09-04T21:58:07Z" Recipient="https://moodle.somewebsite.org/auth/saml2/sp/saml2-acs.php/moodle.somewebsite.org" />
         </SubjectConfirmation>
      </Subject>
      <Conditions NotBefore="2018-09-04T20:18:07Z" NotOnOrAfter="2018-09-04T21:58:07Z">
         <AudienceRestriction>
            <Audience>https://moodle.somewebsite.org/auth/saml2/sp/metadata.php</Audience>
         </AudienceRestriction>
      </Conditions>
      <AttributeStatement>
         <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress">
            <AttributeValue>user@somewebsite.org</AttributeValue>
         </Attribute>
         <Attribute Name="http://schemas.xmlsoap.org/claims/CommonName">
            <AttributeValue>User First Name</AttributeValue>
         </Attribute>
         <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname">
            <AttributeValue>User Last Name</AttributeValue>
         </Attribute>
         <Attribute Name="http://schemas.microsoft.com/ws/2008/06/identity/claims/role">
            <AttributeValue>administrator</AttributeValue>
            <AttributeValue>developer</AttributeValue>
            <AttributeValue>Paramedic</AttributeValue>
         </Attribute>
      </AttributeStatement>
      <AuthnStatement AuthnInstant="2018-09-04T18:38:07Z" SessionIndex="_some_session_index">
         <AuthnContext>
            <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</AuthnContextClassRef>
         </AuthnContext>
      </AuthnStatement>
   </Assertion>
</samlp:Response>
```

in the simplesamllog.php this what is logged

```
Sep 04 21:18:07 SimpleSAMLphp DEBUG [348a976565] Session: 'moodle.somewebsite.org' not valid because we are not authenticated.
Sep 04 21:18:07 SimpleSAMLphp DEBUG [348a976565] Saved state: '_b0a18a3f3a69f3c663607a1e3bc953b4d5a713801d'
Sep 04 21:18:07 SimpleSAMLphp DEBUG [348a976565] Sending SAML 2 AuthnRequest to 'https://somewebsite.org'
Sep 04 21:18:07 SimpleSAMLphp DEBUG [348a976565] Sending message:
[Insert AuthnRequest Here]
Sep 04 21:18:07 SimpleSAMLphp DEBUG [348a976565] Localization: using old system
Sep 04 21:18:08 SimpleSAMLphp DEBUG [348a976565] Received SAML2 Response from 'https://somewebsite.org'.
Sep 04 21:18:08 SimpleSAMLphp DEBUG [348a976565] Has 1 candidate keys for validation.
Sep 04 21:18:08 SimpleSAMLphp DEBUG [348a976565] Validation with key #0 succeeded.
Sep 04 21:18:08 SimpleSAMLphp DEBUG [348a976565] Has 1 candidate keys for validation.
Sep 04 21:18:08 SimpleSAMLphp DEBUG [348a976565] Validation with key #0 succeeded.
[Insert long config here]
Sep 04 21:18:08 SimpleSAMLphp DEBUG [348a976565] Session: doLogin("moodle.somewebsite.org")
Sep 04 21:18:08 SimpleSAMLphp DEBUG [348a976565] Received message: 
[Insert SAML Response form above here Here]
```

This is what is logged in php error log

```
018/09/04 20:18:08 [error] 24601#24601: *151288 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function is_temptable() on null in /home/forge/moodle.somewebsite.org/moodle2/lib/dml/mysqli_native_moodle_database.php:688
Stack trace:
#0 /home/forge/moodle.somewebsite.org/moodle2/lib/dml/moodle_database.php(662): mysqli_native_moodle_database->get_columns('auth_saml2_kvst...')
#1 /home/forge/moodle.somewebsite.org/moodle2/lib/dml/moodle_database.php(1521): moodle_database->where_clause('auth_saml2_kvst...', Array)
#2 /home/forge/moodle.somewebsite.org/moodle2/auth/saml2/classes/store.php(123): moodle_database->get_record('auth_saml2_kvst...', Array)
#3 /home/forge/moodle.somewebsite.org/moodle2/auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/SessionHandlerStore.php(78): auth_saml2\store->set('session', 'c579839e899d176...', 'C%3A18%3A%22Sim...', 1536121088)
#4 /home/forge/moodle.somewebsite.org/moodle2/auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Session.php(453): SimpleSAML\SessionHandlerStore->saveSession(Object(SimpleSAML_Session))
#5" while reading response header from upstream, client: 10.111.111.1, server: moodle.somewebsite.org, request: "POST /auth/saml2/sp/saml2-acs.php/moodle.somewebsite.org HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "moodle.somewebsite.org", referrer: "https://somewebsite.org/postLogin"
```

The above repeats for infinity and the page redirects back and forth for infinity. 

**my question is what is wrong? is this a saml error or a moodle error? is this related to is_temptable()**

**Comment by pkeogan** [comment]
Looks like the error has something to do with session storage and my mariaDB setiup. my IDP is a larvael app and im using laravel forge for hosting.

I installed PHP redis, and used that for storing, and my issue has been fixed. Looks like db storage is broken tho for mariadb

**Comment by ledav78** [comment]
Hi pkeogan, can you describe how you configured the redis storage ?
We have exactly the same comportment as you for the session storage issue. I tried SQL, memcache,...

Tanks !

**Comment by pkeogan** [comment]
@ledav78 

Is your moodle config set correctly?

```
{moodle_root}/config.php
...
$CFG->auth_saml2_store = '\\auth_saml2\\redis_store'; # Use an alternate store
$CFG->auth_saml2_redis_server = '127.0.0.1'; # Required for the redis_store above
...
```

Im running larvael forge's redis setup. Im pretty sure its damn near default.

**Comment by pkeogan** [comment]
@ledav78 

Also, are you getting the same errors I was above in regards `Call to a member function is_temptable() on null`

**Comment by ledav78** [comment]
@pkeogan 
Thank for your help ! Your message forced me to look for another setup bundle of redis.
We were using a version 2.4, now I installed a version 3.2. And everything is working.

Thanks for your answer.

**Comment by brendanheywood** [comment]
Can we close this then?

**Comment by brendanheywood** [comment]
We just found and fixed the is_temptable issue

https://github.com/catalyst/moodle-auth_saml2/commit/60c7e92546917f88bf53abb129b7ed776c6fbcca
