### ISSUE TITLE
Call to a member function real_escape_string() on null

### ISSUE THREAD

**Issue by otatarintseva** [catalyst/moodle-auth_saml2#316]
We use 2017051500 auth_saml2 version with Totara 9. 
We noticed the fatal error on error logs: 

> PHP Fatal error:  Uncaught Error: Call to a member function real_escape_string() on null in /opt/vhosts/sitename
> .com/www/lib/dml/mysqli_native_moodle_database.php:983\nStack trace:\n#0 /opt/vhosts/sitename.com/www/lib/dml/mysqli_native_moodle_database.php(1112): mysqli_native_moodle_database->emulate_
> bound_params('SELECT * FROM m...', Array)\n#1 /opt/vhosts/sitename.com/www/lib/dml/moodle_database.php(1576): mysqli_native_moodle_database->get_records_sql('SELECT * FROM m...', Array, 0, 0)
> \n#2 /opt/vhosts/sitename.com/www/lib/dml/moodle_database.php(1548): moodle_database->get_record_sql('SELECT * FROM {...', Array, 0)\n#3 /opt/vhosts/sitename.com/www/lib/dml/moodle_datab
> ase.php(1527): moodle_database->get_record_select('auth_samltwo_kv...', 'WHERE type = ? ...', Array, '*', 0)\n#4 /opt/vhosts/sitename.com/www/auth/saml2/classes/store.php(129): moodle_databas
> e->get_record('auth_samltwo_kv...', Array)\n#5 /opt/vhosts/sitename.com/www/auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/SessionHandlerStore.p in /opt/vhosts/sitename.com/www/lib/dml/m
> ysqli_native_moodle_database.php on line 983, referer: https://sitename.com/totara/dashboard/index.php

Error backtrace is:

```
array (                                                                                                                                                                                     
  0 =>                                                                                                                                                                                      
  array (                                                                                                                                                                                   
	'file' => '/opt/vhosts/sitename.enovation.ie/www/lib/dml/mysqli_native_moodle_database.php',                                                                                          
	'line' => 1120,                                                                                                                                                                         
	'function' => 'emulate_bound_params',                                                                                                                                                   
	'class' => 'mysqli_native_moodle_database',                                                                                                                                             
	'type' => '->',                                                                                                                                                                         
	'args' =>                                                                                                                                                                               
	array (                                                                                                                                                                                 
	  0 => 'SELECT * FROM mdl_auth_samltwo_kvstore WHERE type = ? AND k = ?',                                                                                                               
	  1 =>                                                                                                                                                                                  
	  array (                                                                                                                                                                               
		0 => 'session',                                                                                                                                                                     
		1 => <sessionId>,                                                                                                                                            
	  ),                                                                                                                                                                                    
	),                                                                                                                                                                                      
  ),                                                                                                                                                                                        
  1 =>                                                                                                                                                                                      
  array (                                                                                                                                                                                   
	'file' => '/opt/vhosts/sitename.enovation.ie/www/lib/dml/moodle_database.php',                                                                                                        
	'line' => 1576,                                                                                                                                                                         
	'function' => 'get_records_sql',                                                                                                                                                        
	'class' => 'mysqli_native_moodle_database',                                                                                                                                             
	'type' => '->',                                                                                                                                                                         
	'args' =>                                                                                                                                                                               
	array (                                                                                                                                                                                 
	  0 => 'SELECT * FROM mdl_auth_samltwo_kvstore WHERE type = ? AND k = ?',                                                                                                               
	  1 =>                                                                                                                                                                                  
	  array (                                                                                                                                                                               
		0 => 'session',                                                                                                                                                                     
		1 => <sessionId>,                                                                                                                                            
	  ),                                                                                                                                                                                    
	  2 => 0,                                                                                                                                                                               
	  3 => 0,                                                                                                                                                                               
	),                                                                                                                                                                                      
  ),                                                                                                                                                                                        
  2 =>                                                                                                                                                                                      
  array (                                                                                                                                                                                   
	'file' => '/opt/vhosts/sitename.enovation.ie/www/lib/dml/moodle_database.php',                                                                                                        
	'line' => 1548,                                                                                                                                                                         
	'function' => 'get_record_sql',                                                                                                                                                         
	'class' => 'moodle_database',                                                                                                                                                           
	'type' => '->',                                                                                                                                                                         
	'args' =>                                                                                                                                                                               
	array (                                                                                                                                                                                 
	  0 => 'SELECT * FROM {auth_samltwo_kvstore} WHERE type = ? AND k = ?',                                                                                                                 
	  1 =>                                                                                                                                                                                  
	  array (                                                                                                                                                                               
		0 => 'session',                                                                                                                                                                     
		1 => <sessionId>,                                                                                                                                            
	  ),                                                                                                                                                                                    
	  2 => 0,                                                                                                                                                                               
	),                                                                                                                                                                                      
  ),
3 =>                                                                                                                                                                                      
  array (                                                                                                                                                                                   
	'file' => '/opt/vhosts/sitename.enovation.ie/www/lib/dml/moodle_database.php',                                                                                                        
	'line' => 1527,                                                                                                                                                                         
	'function' => 'get_record_select',                                                                                                                                                      
	'class' => 'moodle_database',                                                                                                                                                           
	'type' => '->',                                                                                                                                                                         
	'args' =>                                                                                                                                                                               
	array (                                                                                                                                                                                 
	  0 => 'auth_samltwo_kvstore',                                                                                                                                                          
	  1 => 'WHERE type = ? AND k = ?',                                                                                                                                                      
	  2 =>                                                                                                                                                                                  
	  array (                                                                                                                                                                               
		0 => 'session',                                                                                                                                                                     
		1 => <sessionId>,                                                                                                                                            
	  ),                                                                                                                                                                                    
	  3 => '*',                                                                                                                                                                             
	  4 => 0,                                                                                                                                                                               
	),                                                                                                                                                                                      
  ),                                                                                                                                                                                        
  4 =>                                                                                                                                                                                      
  array (                                                                                                                                                                                   
	'file' => '/opt/vhosts/sitename.enovation.ie/www/auth/saml2/classes/store.php',                                                                                                       
	'line' => 129,                                                                                                                                                                          
	'function' => 'get_record',                                                                                                                                                             
	'class' => 'moodle_database',                                                                                                                                                           
	'type' => '->',                                                                                                                                                                         
	'args' =>                                                                                                                                                                               
	array (                                                                                                                                                                                 
	  0 => 'auth_samltwo_kvstore',                                                                                                                                                          
	  1 =>                                                                                                                                                                                  
	  array (                                                                                                                                                                               
		'type' => 'session',                                                                                                                                                                
		'k' => <sessionId>,                                                                                                                                          
	  ),                                                                                                                                                                                    
	),                                                                                                                                                                                      
  ),                                                                                                                                                                                        
  5 =>                                                                                                                                                                                      
  array (                                                                                                                                                                                   
	'file' => '/opt/vhosts/sitename.enovation.ie/www/auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/SessionHandlerStore.php',                                                             
	'line' => 76,                                                                                                                                                                           
	'function' => 'set',                                                                                                                                                                    
	'class' => 'auth_saml2\\store',                                                                                                                                                         
	'type' => '->',                                                                                                                                                                         
	'args' =>                                                                                                                                                                               
	array (                                                                                                                                                                                 
	  0 => 'session',                                                                                                                                                                       
	  1 => <sessionId>,                                                                                                                                              
	  2 => <session>,                                                                     
	  3 => 1552348536,                                                                                                                                                                      
	),                                                                                                                                                                                      
  ),
  6 =>                                                                                                                                                                                      
  array (                                                                                                                                                                                   
	'file' => '/opt/vhosts/sitename.enovation.ie/www/auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Session.php',                                                                         
	'line' => 433,                                                                                                                                                                          
	'function' => 'saveSession',                                                                                                                                                            
	'class' => 'SimpleSAML_SessionHandlerStore',                                                                                                                                            
	'type' => '->',                                                                                                                                                                         
	'args' =>                                                                                                                                                                               
	array (                                                                                                                                                                                 
	  0 =>                                                                                                                                                                                  
	  SimpleSAML_Session::__set_state(array(                                                                                                                                                
		 'sessionId' => <sessionId>,                                                                                                                                 
		 'transient' => false,                                                                                                                                                              
		 'trackid' => <trackid>,                                                                                                                                                         
		 'rememberMeExpire' => NULL,                                                                                                                                                        
		 'dirty' => false,                                                                                                                                                                  
		 'callback_registered' => false,                                                                                                                                                    
		 'dataStore' => NULL,                                                                                                                                                               
		 'associations' =>                                                                                                                                                                  
		array (                                                                                                                                                                             
		),                                                                                                                                                                                  
		 'authToken' => NULL,                                                                                                                                                               
		 'authData' =>                                                                                                                                                                      
		array (                                                                                                                                                                             
		),                                                                                                                                                                                  
	  )),                                                                                                                                                                                   
	),                                                                                                                                                                                      
  ),                                                                                                                                                                                        
  7 =>                                                                                                                                                                                      
  array (                                                                                                                                                                                   
	'file' => '/opt/vhosts/sitename.enovation.ie/www/auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Session.php',                                                                         
	'line' => 494,                                                                                                                                                                          
	'function' => 'save',                                                                                                                                                                   
	'class' => 'SimpleSAML_Session',                                                                                                                                                        
	'type' => '->',                                                                                                                                                                         
	'args' =>                                                                                                                                                                               
	array (                                                                                                                                                                                 
	),                                                                                                                                                                                      
  ),                                                                                                                                                                                        
  8 =>                                                                                                                                                                                      
  array (                                                                                                                                                                                   
	'function' => '__destruct',                                                                                                                                                             
	'class' => 'SimpleSAML_Session	',                                                                                                                                                        
	'type' => '->',                                                                                                                                                                         
	'args' =>                                                                                                                                                                               
	array (                                                                                                                                                                                 
	),                                                                                                                                                                                      
  ),                                                                                                                                                                                        
)  
```  

We debugged the $DB variable auth/saml2/classes/store.php in set() method and it looks like already destroyed and mysqli property is NULL.

```
// in auth/saml2/classes/store.php 
// public function set() 
//after global $DB, $CFG;

mysqli_native_moodle_database::__set_state(array(                                                                                                                                           
   'mysqli' => NULL,                                                                                                                                                                        
   'compressedrowformatsupported' => NULL,                                                                                                                                                  
   'transactions_supported' => NULL,                                                                                                                                                        
   'serverinfo' =>                                                                                                                                                                          
  array (                                                                                                                                                                                   
	'description' => '5.7.24-0ubuntu0.16.04.1-log',                                                                                                                                         
	'version' => '5.7.24-0ubuntu0.16.04.1-log',                                                                                                                                             
  ),                                                                                                                                                                                        
   'database_manager' => NULL,                                                                                                                                                              
   'temptables' => NULL,                                                                                                                                                                    
   'tables' => NULL,                                                                                                                                                                        
   'dbhost' => 'localhost',                                                                                                                                                                 
   'dbuser' => <dbuser>,                                                                                                                                                         
   'dbpass' => <dbpass>,                                                                                                                                                             
   'dbname' => <dbname>,                                                                                                                                                         
   'prefix' => 'mdl_',                                                                                                                                                                      
   'dboptions' =>                                                                                                                                                                           
  array (                                                                                                                                                                                   
	'dbpersist' => false,                                                                                                                                                                   
	'dbsocket' => false,                                                                                                                                                                    
	'dbport' => '',                                                                                                                                                                         
  ),                                                                                                                                                                                        
   'external' => false,                                                                                                                                                                     
   'reads' => 13,                                                                                                                                                                           
   'writes' => 6,                                                                                                                                                                           
   'queriestime' => 0.020060300827026367,                                                                                                                                                   
   'debug' => 0,                                                                                                                                                                            
   'last_sql' => NULL,                                                                                                                                                                      
   'last_params' => NULL,                                                                                                                                                                   
   'last_type' => 2,                                                                                                                                                                        
   'last_extrainfo' => NULL,                                                                                                                                                                
   'last_time' => 1552322107.122323,                                                                                                                                                        
   'loggingquery' => false,                                                                                                                                                                 
   'used_for_db_sessions' => false,                                                                                                                                                         
   'transactions' =>                                                                                                                                                                        
  array (                                                                                                                                                                                   
  ),                                                                                                                                                                                        
   'force_rollback' => false,                                                                                                                                                               
   'settingshash' => <settingshash>,                                                                                                                                    
   'metacache' => NULL,                                                                                                                                                                     
   'disposed' => true,                                                                                                                                                                      
   'fix_sql_params_i' => NULL,                                                                                                                                                              
   'replacetextuniqueindex' => 1,                                                                                                                                                           
)) 
```

The values are replaced with `<variable>`

Could you please fix this issue?

**Comment by danmarsden** [comment]
closing this, but if this is an issue with T12 or higher please let us know and we can reopen again.
