### ISSUE TITLE
Some possible suggestions due to error displayed in moodle

### ISSUE THREAD

**Issue by katcher** [catalyst/moodle-auth_saml2#433]
**What happened?**
moodle 3.9

We have a test site that we want to restrict to Faculty/Staff only.
I asked my adfs admin to configure authentication for this site to only Faculty/staff.  If a user was not, it would return false.

Attempted login with staff account worked
Login with student account got the following error:

SAML2 exception: Responder/RequestDenied

More information about this error

×Debug info: #0 [dirroot]/auth/saml2/extlib/simplesamlphp/modules/saml/lib/Message.php(590): SimpleSAML\Module\saml\Message::getResponseError(Object(SAML2\Response))
#1 [dirroot]/auth/saml2/extlib/simplesamlphp/modules/saml/www/sp/saml2-acs.php(134): SimpleSAML\Module\saml\Message::processResponse(Object(SimpleSAML\Configuration), Object(SimpleSAML\Configuration), Object(SAML2\Response))
#2 [dirroot]/auth/saml2/sp/saml2-acs.php(32): require('[dirroot]...')
#3 {main}
Error code: exception
×Stack trace:
line 34 of /auth/saml2/sp/saml2-acs.php: saml2_exception thrown

From what I can understand, the response was sent back from our adfs server to the test moodle sever but since it was a student, no token was provided and although valid login, invalid response.

** Expected outcome **
I would have hoped that either the response from adfs would have been authentication failed and it would not go back to my moodle site.  Since the response was returned to the moodle site,  I would have expected a user friendly error - "You are not permitted access to this site".

Am I missing something in my configuration on Moodle.

I am including another issue-improvement as it is related.

Issue 2
**What happened**
Rather than having ADFS determine valid user or not, I used the gui in the plugin to restrict role to a group.  This worked as well except when I tried to login as a student, the user was denied access but the logout message had a logout url.  Since we use a custom logout, it did not appear to log the user out.  Every subsequent time I tried to login I got the error.  I had to delete the cookies to continue.

Is there some way, if a custom logout is used, could the logout from the "Response message" point to the Alternative Logout URL only if configured? 

Thanks

Eric K

**Comment by brendanheywood** [comment]
thanks Eric,

1) That seems valid and just a use case I've never seen before. Yes normally you just never make it back to the SP. Pull requests welcome

2) This feels like the wrong approach but I'd need more details. You should always logout of moodle, and then moodle calls logoutpage_hook in the auth plugin you are using. This plugin does exactly that which logs out of both moodle and then back to the IdP to log out of it too. Your custom logout should be hidden behind the Idp and moodle shouldn't be aware of it directly, it's all handled by the SingleLogoutService in your IdP's metadata xml.

I'd normally suggest split this into a second issue as they are technically independent, but I suspect the second one will be a 'won't do'

**Comment by katcher** [comment]
Hi Brendan, is there anything you need me to provide?  PS we are a client of both catalyst australia and NZ.

**Comment by brendanheywood** [comment]
hi @katcher its better if you can make a Work Request and stick all the exact details in it which you probably don't want to share publicly here, and also reference this issue in the WR (and feel free to add me as a watcher too)

**Comment by brendanheywood** [comment]
Related to https://github.com/catalyst/moodle-auth_saml2/issues/488

**Comment by katcher** [comment]
Well Brendan, It seems that this error message has begun showing up again since we are trying to implement **MFA**.  It is sporadic.  When I encounter the error I would clear all cookies and attempt to log in again.  In most cases it would work.  But this is not reliable.  I removed the passive mode.

Likely show stopper for MFA.

I have created a ticket on wrms.

**Comment by brendanheywood** [comment]
@katcher I haven't seen the WR can you please add me as a watcher there?
