### ISSUE TITLE
SAML2 exception: ACSPARAMS when switching tenants in MWP

### ISSUE THREAD

**Issue by daniel-hefley** [catalyst/moodle-auth_saml2#800]
Platform: [Moodle Workplace 4.1.2+ (Build: 20230417)]
SAML2: 2023100300
```
Error: 
Debug info: #0 [dirroot]/auth/saml2/sp/saml2-acs.php(37): SimpleSAML\Module\saml\Controller\ServiceProvider->assertionConsumerService()
#1 {main}
Error code: exception

Stack trace:
line 40 of /auth/saml2/sp/saml2-acs.php: saml2_exception thrown
```

Single idP (Okta)
2 tenants
Tenant availability: This IdP is available to all tenants (including future ones)

To replicate:
1. Log into Okta and access dashboard.
2. Select app to access MWP leaving tab open.
3. Directed to MWP (opens in new tab).
4. Change tenant in MWP.
5. Logout of MWP and close tab.
6. Return to Okta dashboard and select app again.
7. Directed to MWP (in new tab) but get above error.

Also seeing the below error in the simplesamlphp.log file. Not sure if it is related but including it here just in case.

```
Feb 14 12:59:36 31.94.32.37 SimpleSAMLphp WARNING [65f6e256a7] Unsuccessful logout. Status was: SimpleSAML\Module\saml\Error: AuthnFailed in /var/www/moodle_workplace/auth/saml2/.extlib/simplesamlphp/modules/saml/lib/Message.php:503
Stack trace:
#0 /var/www/moodle_workplace/auth/saml2/.extlib/simplesamlphp/modules/saml/www/sp/saml2-logout.php(72): SimpleSAML\Module\saml\Message::getResponseError()
#1 /var/www/moodle_workplace/auth/saml2/sp/saml2-logout.php(59): require('...')
#2 {main}
```

Okta configuration:
<img width="702" alt="1" src="https://github.com/catalyst/moodle-auth_saml2/assets/5255531/5febde5a-cb94-4e42-a0e1-dc7939e14875">

<img width="701" alt="2" src="https://github.com/catalyst/moodle-auth_saml2/assets/5255531/dd96ff3d-95a3-417d-833a-35a26a1c3a7c">

![3](https://github.com/catalyst/moodle-auth_saml2/assets/5255531/e7f04606-a4f9-4f83-ae95-55e392a45eff)

![4](https://github.com/catalyst/moodle-auth_saml2/assets/5255531/33b6fcc3-9d22-43fe-a86c-7a0a15f1cb12)

<img width="700" alt="5" src="https://github.com/catalyst/moodle-auth_saml2/assets/5255531/1d055991-c409-4192-a824-dcbad441871e">

SAML2 configuration in MWP:

![saml2_config](https://github.com/catalyst/moodle-auth_saml2/assets/5255531/ef44b0ed-7c31-4ed8-b959-4f5ae34b498b)

**Comment by danmarsden** [comment]
Hi @daniel-hefley - thanks for the report - we don't have many of our own clients using OKTA and our saml plugin - if you work out what's going wrong, feel free to submit a PR or reach out privately if you would like commercial level support to investigate it further.

thanks!
