### ISSUE TITLE
Saml2 logout error message rising from AssertionConsumerService

### ISSUE THREAD

**Issue by paulortman** [catalyst/moodle-auth_saml2#818]
When explicitly logging out an error message is generated:

```
SAML2 exception: BADREQUEST('%REASON%' =&gt; 'Invalid message received at AssertionConsumerService endpoint.')
Debug info: #0 [dirroot]/auth/saml2/sp/saml2-acs.php(37): SimpleSAML\Module\saml\Controller\ServiceProvider->assertionConsumerService()
#1 {main}
Error code: exception
Stack trace:
line 40 of /auth/saml2/sp/saml2-acs.php: saml2_exception thrown
```

The account appears to be logged out, but the error message is a bit unsettling.

Running:
Moodle 4.4+ (Build: 20240516)
PHP 8.3.7
auth_saml2 2024051700

**Comment by gturetchi** [comment]
> When explicitly logging out an error message is generated:
> 
> ```
> SAML2 exception: BADREQUEST('%REASON%' =&gt; 'Invalid message received at AssertionConsumerService endpoint.')
> Debug info: #0 [dirroot]/auth/saml2/sp/saml2-acs.php(37): SimpleSAML\Module\saml\Controller\ServiceProvider->assertionConsumerService()
> #1 {main}
> Error code: exception
> Stack trace:
> line 40 of /auth/saml2/sp/saml2-acs.php: saml2_exception thrown
> ```
> 
> The account appears to be logged out, but the error message is a bit unsettling.
> 
> Running: Moodle 4.4+ (Build: 20240516) PHP 8.3.7 auth_saml2 2024051700

You managed to run this plugin for latest moodle ? 
After I recive the saml response and redirected to auth/saml2/login.php?wants&idp=.... I recive 500, internal server error

**Comment by jcmoodle** [comment]
I am receiving a similar error on logout and a different error on login.

Running: 
Moodle 4.1.14 
PHP 7.4.33
auth_saml2 (2024090900)

Logout:
```
SAML2 exception: BADREQUEST('%REASON%' =&gt; 'Invalid message received at AssertionConsumerService endpoint.')

More information about this error

Debug info: #0 [dirroot]/auth/saml2/sp/saml2-acs.php(37): SimpleSAML\Module\saml\Controller\ServiceProvider->assertionConsumerService('moodle.domain.com')
#1 {main}
Error code: exception×Dismiss this notification
Stack trace:
line 40 of /auth/saml2/sp/saml2-acs.php: saml2_exception thrown
```

Login:
```
SAML2 exception: ACSPARAMS

More information about this error

Debug info: #0 [dirroot]/auth/saml2/sp/saml2-acs.php(37): SimpleSAML\Module\saml\Controller\ServiceProvider->assertionConsumerService('moodle.domain.com')
#1 {main}
Error code: exception×Dismiss this notification
Stack trace:
line 40 of /auth/saml2/sp/saml2-acs.php: saml2_exception thrown
```

In our case the account does login and logout, but the errors are still present. 

Please advise.
